### ISSUE TITLE
INFOGRAFIA

### ISSUE THREAD

**Issue by MAB288** [SistemasTecTlaxiaco/actividad-1-infografia-MAB288-1#1]
[INFOGRAFIA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-MAB288-1/files/14249715/INFOGRAFIA.pdf)

**Comment by Luz1727** [comment]
Calificacion: 20 /20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
